name: Deploy Hexo Blog

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Hexo
        run: 
          npm install hexo-cli -g
          npm install

      - name: Generate Static Files
        run: 
          hexo clean
          hexo generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages  # 指定部署分支
          keep_files: false  # 完全覆盖目标分支
          
      - name: Install Dependencies
        run: 
          # 确保存在package.json
          if [ ! -f package.json ]; then
            npm init -y
            echo "Created new package.json"
          fi

        # 安装核心依赖
          npm install hexo-cli --save
          npm install hexo --save
        
        # 安装其他依赖（如果有）
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi