- name: Deploy
  run: |
    git clone https://${{ secrets.HEXO_DEPLOY_TOKEN }}@github.com/yukangzhi/yukangzhi.github.io.git public
    cd public
    git rm -rf .  # 清空目标仓库
    cp -r ../public/* .  # 复制生成的静态文件
    git add .
    git commit -m "Deploy by GitHub Actions"
    git push origin main