name: Deploy Hexo Blog

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Hexo
        run: |
          npm install hexo-cli -g
          npm install

      - name: Generate Static Files
        run: |
          hexo clean
          hexo generate

      - name: Deploy
        env:
          GIT_USER: "GitHub Actions Bot"
          GIT_EMAIL: "actions@github.com"
          REPO_URL: "https://${{ secrets.HEXO_DEPLOY_TOKEN }}@github.com/yukangzhi/yukangzhi.github.io.git"
        run: |
          git config --global user.name "$GIT_USER"
          git config --global user.email "$GIT_EMAIL"
          git clone $REPO_URL public-deploy
          cd public-deploy
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          cp -r ../public/* .
          git add .
          git commit -m "Deploy by GitHub Actions"
          git push origin main